/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace MeCab {

using System;
using System.Runtime.InteropServices;

public class MeCab {
  public static readonly int MECAB_NOR_NODE = MeCabPINVOKE.MECAB_NOR_NODE_get();
  public static readonly int MECAB_UNK_NODE = MeCabPINVOKE.MECAB_UNK_NODE_get();
  public static readonly int MECAB_BOS_NODE = MeCabPINVOKE.MECAB_BOS_NODE_get();
  public static readonly int MECAB_EOS_NODE = MeCabPINVOKE.MECAB_EOS_NODE_get();
  public static readonly int MECAB_EON_NODE = MeCabPINVOKE.MECAB_EON_NODE_get();
  public static readonly int MECAB_USR_DIC = MeCabPINVOKE.MECAB_USR_DIC_get();
  public static readonly int MECAB_SYS_DIC = MeCabPINVOKE.MECAB_SYS_DIC_get();
  public static readonly int MECAB_UNK_DIC = MeCabPINVOKE.MECAB_UNK_DIC_get();
  public static readonly string VERSION = MeCabPINVOKE.VERSION_get();
}

}
