/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.chasen.mecab;

public interface MeCabConstants {
  public final static int MECAB_NOR_NODE = MeCabJNI.MECAB_NOR_NODE_get();
  public final static int MECAB_UNK_NODE = MeCabJNI.MECAB_UNK_NODE_get();
  public final static int MECAB_BOS_NODE = MeCabJNI.MECAB_BOS_NODE_get();
  public final static int MECAB_EOS_NODE = MeCabJNI.MECAB_EOS_NODE_get();
  public final static int MECAB_EON_NODE = MeCabJNI.MECAB_EON_NODE_get();
  public final static int MECAB_USR_DIC = MeCabJNI.MECAB_USR_DIC_get();
  public final static int MECAB_SYS_DIC = MeCabJNI.MECAB_SYS_DIC_get();
  public final static int MECAB_UNK_DIC = MeCabJNI.MECAB_UNK_DIC_get();
  public final static String VERSION = MeCabJNI.VERSION_get();
}
