/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.chasen.mecab;

public class Token {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected Token(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Token obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        throw new UnsupportedOperationException("C++ destructor does not have public access");
      }
      swigCPtr = 0;
    }
  }

  public int getLcAttr() {
    return MeCabJNI.Token_lcAttr_get(swigCPtr, this);
  }

  public int getRcAttr() {
    return MeCabJNI.Token_rcAttr_get(swigCPtr, this);
  }

  public int getPosid() {
    return MeCabJNI.Token_posid_get(swigCPtr, this);
  }

  public short getWcost() {
    return MeCabJNI.Token_wcost_get(swigCPtr, this);
  }

  public long getFeature() {
    return MeCabJNI.Token_feature_get(swigCPtr, this);
  }

  public long getCompound() {
    return MeCabJNI.Token_compound_get(swigCPtr, this);
  }

}
